name: Add milestone on open
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    branches: [main]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          farthest: true  # remove this line to add the current milestone
          overwrite: true # remove this line to keep an existing milestone
          single: true    # remove this line if you have multiple milestones
                          # open at a time and use due dates
