name: Add milestone on merge
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  add:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          overwrite: true # remove this line to keep existing milestone
